# Generated by Django 4.0.4 on 2022-05-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_url'),
    ]

    operations = [
    ]
